src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


// TODO: Add relation with user when user is created 


/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull
     * @Assert\Length(
     *  min = 1,
     *  max = 255,
     *  minMessage = "Product name must be at least {{ limit }} characters long",
     *  maxMessage = "Product name cannot be longer than {{ limit }} characters"
     * )
     */
    private $Nom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $Description;
    
    /**
     * @ORM\Column(type="float")
     * @Assert\PositiveOrZero
     */
    private $Prix;

    /**
     * @ORM\Column(type="integer")
     * @Assert\PositiveOrZero
     */
    private $Stock;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Photo;

    /**
     * @ORM\ManyToMany(targetEntity=ContenuPanier::class, mappedBy="Produit")
     */
    private $contenuPaniers;

    public function __construct()
    {
        $this->contenuPaniers = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->Prix;
    }

    public function setPrix(float $Prix): self
    {
        $this->Prix = $Prix;

        return $this;
    }

    public function getStock(): ?int
    {
        return $this->Stock;
    }

    public function setStock(int $Stock): self
    {
        $this->Stock = $Stock;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->Photo;
    }

    public function setPhoto(?string $Photo): self
    {
        $this->Photo = $Photo;

        return $this;
    }

    /**
     * @return Collection|ContenuPanier[]
     */
    public function getContenuPaniers(): Collection
    {
        return $this->contenuPaniers;
    }

    public function addContenuPanier(ContenuPanier $contenuPanier): self
    {
        if (!$this->contenuPaniers->contains($contenuPanier)) {
            $this->contenuPaniers[] = $contenuPanier;
            $contenuPanier->addProduit($this);
        }

        return $this;
    }

    public function removeContenuPanier(ContenuPanier $contenuPanier): self
    {
        if ($this->contenuPaniers->contains($contenuPanier)) {
            $this->contenuPaniers->removeElement($contenuPanier);
            $contenuPanier->removeProduit($this);
        }

        return $this;
    }

    public function __toString()
    {
        return $this->Nom;
    }
}

src/Form/ProduitType.php
<?php

namespace App\Form;

use App\Entity\Produit;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class ProduitType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Nom')
            ->add('Description')
            ->add('Prix')
            ->add('Stock')
            ->add('Photo', FileType::class, [
                'required' => false,
                'mapped' => false
            ])
            ->add('save', SubmitType::class);

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Produit::class,
        ]);
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;

use App\Entity\Produit;
use App\Form\ProduitType;
use App\Entity\ContenuPanier;
use App\Form\ContenuPanierType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Translation\TranslatorInterface;


class ProduitController extends AbstractController
{
    /**
     * @Route("/", name="produits")
     */
    public function index(Request $request, TranslatorInterface $translator)
    {
        $em = $this->getDoctrine()->getManager();

        $produit = new Produit();
        $form = $this->createForm(ProduitType::class, $produit);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {

            $fichier = $form->get('Photo')->getData();

            if ($fichier) {

                $nomFichier = uniqid() . '.' . $fichier->guessExtension();

                try {
                    $fichier->move(
                        $this->getParameter('upload_dir'),
                        $nomFichier
                    );
                } catch (FileException $e) {
                    $this->addFlash('danger', 'Impossible de déplacer le fichier');
                    echo 'Impossible de déplacer le fichier';
                }

                $produit->setPhoto($nomFichier);
            }

            $em->persist($produit);
            $em->flush();

            $this->addFlash('success', $translator->trans('Produit crée'));
        }
        $produit = $em->getRepository(Produit::class)->findAll();

        return $this->render('produit/index.html.twig', [
            'produits' => $produit,
            'ajout_produit' => $form->createView()
        ],);
    }

    /**
     * @Route("/produits/info/{id}", name="produit_details")
     */
    public function info(Request $request, Produit $produit = null, TranslatorInterface $translator)
    {
        if ($produit != null) {

            $form = $this->createForm(ProduitType::class, $produit);

            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $pdo = $this->getDoctrine()->getManager();

                $pdo->persist($produit);  // prepare en PDO
                $pdo->flush();              // execute en PDO

            }

            return $this->render('produit/produit.html.twig', [
                'produit'         => $produit,
                'produit_details'    => $form->createView()
            ]);
        } else {

            $this->addFlash('danger', $translator->trans('Produit introuvable'));
            return $this->redirectToRoute('produits');
        }
    }

    /**
     * @Route("/produits/edit/{id}", name="produit_edit")
     */
    public function edit(Request $request, Produit $produit = null, TranslatorInterface $translator)
    {
        if ($produit != null) {

            $form = $this->createForm(ProduitType::class, $produit);

            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $pdo = $this->getDoctrine()->getManager();

                $pdo->persist($produit);  // prepare en PDO
                $pdo->flush();              // execute en PDO

            }

            return $this->render('produit/produit.html.twig', [
                'produit'         => $produit,
                'produit_details'    => $form->createView()
            ]);
        } else {

            $this->addFlash('danger', $translator->trans('Produit introuvable'));
            return $this->redirectToRoute('produits');
        }
    }

    /**
     * @Route("/produits/delete/{id}", name="produit_delete")
     */
    public function delete(Produit $produit = null, TranslatorInterface $translator)
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN', null, 'User tried to access a page without having ROLE_ADMIN');

        if ($produit != null) {

            $em = $this->getDoctrine()->getManager();
            $em->remove($produit);
            $em->flush();
            $this->addFlash('warning', $translator->trans('Produit supprimé'));
        } else {
            $this->addFlash('danger', $translator->trans('Produit introuvable'));
        }

        return $this->redirectToRoute('produits');
    }

    /**
     * @Route("/panier/{id}", name="add_panier")
     */
    public function produit(Request $request, Produit $produit=null, TranslatorInterface $translator)
    {
        if($produit != null){
            $panier = new ContenuPanier();
            $form = $this->createForm(ContenuPanierType::class, $panier);
            $form->handleRequest($request);
            dump($form);
            if($form->isSubmitted() && $form->isValid()){
                $em = $this->getDoctrine()->getManager();                
                $panier->setProduit($produit);
                $panier->setQuantite(1);
                $em->persist($panier);
                $em->flush();
    
                $this->addFlash('success', $translator->trans("Produit ajouté"));
            }

            return $this->render('contenu_panier/index.html.twig', [
                'paniers'      => $panier,
                'ajout_produit' => $form->createView()
            ]);
        }
        else{
            $this->addFlash('danger', $translator->trans("Produit introuvable"));
            return $this->redirectToRoute('produits');
        }
    }
}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}

    {% if produits is not empty %}
        <table class="table">
            <thead>
                <tr>
                    <th>Photo</th>
                    <th>{{ 'produit.nom'|trans }}</th>
                    <th>{{ 'produit.description'|trans }}</th>
                    <th>{{ 'produit.prix'|trans }}</th>
                    <th>{{ 'produit.stock'|trans }}</th>
                </tr>
            </thead>
            <tbody>
                {% for produit in produits %}
                    <tr>
                        <td>
                        {% if produit.photo is not empty %}
                            <img src="{{asset('uploads/'~ produit.photo)}}" style="max-width: 200px;">
                        {% endif %}
                        </td>
                        <td>   
                            <a href="{{ path( 'produit_details', {'id': produit.id} ) }}">
                                {{produit.nom}}
                            </a>                        
                        </td>
                        <td>
                            {{produit.Description}}
                        </td>
                        <td>
                            {{produit.Prix}}
                        </td>
                        <td>
                            {{produit.Stock}}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
    <p>{{ 'produit.noProd'|trans }}</p>
    {% endif %}
        
    {% if is_granted('ROLE_ADMIN') %}
        <h2>{{ 'produit.addProd'|trans }}</h2>
        {{form(ajout_produit)}}
    {% endif %}


{% endblock %}

templates/produit/produit.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{produit.nom}} {% endblock %}

{% block body %}
	<h1>{{produit.Nom}}</h1>

	{% if produit.Photo is not empty %}
		<img src="{{asset('uploads/'~ produit.photo)}}" style="max-width: 200px;">
	{% endif %}

	<h2>{{ 'produit.prix'|trans }} : {{produit.Prix}}</h2>
	<h2>{{ 'produit.stock'|trans }} : {{produit.Stock}}</h2>

	<a href="{{path('add_panier', {'id':produit.id})}}" class="btn btn-success">{{ 'Add item'|trans }}</a>
	{% if is_granted('ROLE_ADMIN') %}
	<a href="{{path('produit_delete', {'id':produit.id})}}" class="btn btn-danger">{{ 'Delete'|trans }}</a>
	{% endif %}

	
	{% if is_granted('ROLE_ADMIN') %}
		<a href="{{path('produit_delete', {'id':produit.id})}}" class="btn btn-danger">{{ 'Delete'|trans }}</a>
		<h2>{{ 'Edit:'|trans }}</h2>    
		{{form(produit_details)}}

	{% endif %}

{% endblock %}